"""
Django settings for mi_blog_noticias project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-**ccu==o!-2umxc6d_&b+(e2&@h3fb5c6kx=+8es9v0c97v_wy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'https://johac.pythonanywhere.com/']#antes estaba vacio


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'crispy_forms',     # 'crispy_bootstrap5', # Si usas Bootstrap 5
    'crispy_bootstrap5',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_blog_noticias.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.categorias_globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_blog_noticias.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/' # Redirige a la página principal después de iniciar sesión
LOGOUT_REDIRECT_URL = '/' # Redirige a la página principal después de cerrar sesión
LOGIN_URL = '/login/'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Crea una carpeta 'media' en la raíz de tu proyecto

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" # Si usas Bootstrap 5
CRISPY_TEMPLATE_PACK = "bootstrap5" # Si usas Bootstrap 5

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Configuración de Correo Electrónico (para desarrollo) imprimirá los correos en la consola.

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'arg.formativa.arg@gmail.com' # ¡CAMBIA ESTO por tu dirección de Gmail!
# EMAIL_HOST_PASSWORD = 'vwgk zeym avpd wlbi' # Tu contraseña de aplicación de Gmail
# DEFAULT_FROM_EMAIL = 'arg.formativa.arg@gmail.com' # La dirección que aparecerá como remitente por defecto

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Asegúrate de que esté en False cuando uses TLS
EMAIL_HOST_USER = 'arg.formativa.arg@gmail.com'
EMAIL_HOST_PASSWORD = 'vwgk zeym avpd wlbi'  # Tu contraseña de aplicación
DEFAULT_FROM_EMAIL = 'arg.formativa.arg@gmail.com'
SERVER_EMAIL = 'arg.formativa.arg@gmail.com'  # Para emails de error del servidor

SITE_ID = 1

# Configuración del nombre del sitio
SITE_NAME = 'Huellitas'